### ISSUE TITLE
Probleme mit Elster

### ISSUE THREAD

**Issue by Kletzsch** [Thomas-Mielke-Software/ECTElster#2]
Beim Aufruf der Elster werden Fehler angezeigt bezüglich der Formatierung. Sie beziehen sich zum Beipsile auf die Eingabe der Zahlen. Die Eingabemaske lässt ja nur ein eingabe mit Punkten zu. Beispiel: 500.00 Euro. Aber die Fehlermeldung bemängelt das und will kommas haben. ????
Gruße
Matthias Kletzsch
![problems elster upload](https://github.com/Thomas-Mielke-Software/ECTElster/assets/162810333/6215df09-0fe4-4e30-b124-50cc7369958b)

**Comment by thomiel** [comment]
Kann es sein, dass englische oder schweitzer Lokalisierung in Windows eingestellt ist? Aber intern wird auf jeden Fall in Festkommazahlen umgewandelt.

Kurios!

**Comment by thomiel** [comment]
Ich gehe davon aus, dass das Problem gelöst ist, weil [im Forum](https://easyct.de/forum/viewthread.php?thread_id=4290) auch nichts mehr kam. Ansonsten bitte neu öffnen!
