### ISSUE TITLE
ÊÜR Feld 1240

### ISSUE THREAD

**Issue by Rainer6767** [Thomas-Mielke-Software/ECTElster#3]
Feld 1240 wird im Elster Formular EÜRE 2023 nicht verarbeitet.

Steuerfreie Einnahmen nach § 3 Nr. 26 EStG habe ich in den allg. Betriebseinnahmen eingegeben. Die Steuerfreiheit in Höhe von 3.000 € ist als Abzugsbetrag bei der Gewinnermittlung zu berücksichtigen. Ich habe ein Konto angelegt mit Feld 1240. In der EÜR habe ich jetzt eine Differenz von 3.000 €, weil BE minus BA natürlich nicht dem korrigierten Gewinn entspricht.

**Comment by thomiel** [comment]
Bei Dir wird es nicht aufsummiert in Zeile 90?

Oder wenn es Dir um die Freestyle-EÜR geht, die durch die Nebeneinkünfte verfälscht wird, nimm einen Kontennamen mit '/' am Anfang.

Ansonsten musst Du mal genau auflisten wo falsche Zahlen auftreten und wie das zu korrigieren wäre (am Besten mit Phantasiezahlen wegen Steuergeheimnis).

**Comment by Rainer6767** [comment]
Hallo Thomas,
ja genau. Das Konto habe ich als Ausgabenkonto angelegt mit Zuordnung zu Feld 1240, eingetragen habe ich den Freibetrag von 3.000 € nach § 3 Nr. 26 EStG.
In der Gewinnermittlung in ELSTER wird es einfach nicht berücksichtigt. 
Meine Honorare, die ich an Hochschulen bekomme, habe ich ordnungsgemäß als Betriebseinnahmen verbucht. DIe Logik der EÜR ist, dass der steuerfreie Anteil davon (also eben die 3.000 €) in Zeile 75 abgezogen wird.
Das Formular in ECT macht das auch korrekt.
Nur beim ELSTER Formular klappt es nicht, ich bekomme eine Fehlermeldung, weil im ELSTER Formular der Gewinn nicht der Differenz aus Einnahmen und Ausgaben entspricht. Der Gewinn in ELSTER wird korrekt aus ECT übernommen, also gemindert um die 3.000 Freibetrag. Aber das rechnet sich in ELSTER eben nicht, weil dort nur die Betriebseinnahmen und die Betriebsausgaben übernommmen werden.

Fiktives Beispiel:
ECT: BE 10.000 minus BA 2.000 minus 3.000 steuerfreie Einnahmen (Zeile 75) = Gewinn 5.000 € (Zeile 90)
ELSTER (in ECT): BE 10.000 minus BA 2.000 = Gewinn 5.000 € --> Fehlermeldung, weil Formel nicht aufgeht.

Das Problem liegt nicht am ECT Formular für die EÜR, sondern nur beim Export in ELSTER

Viele Grüße

**Comment by thomiel** [comment]
Hmm, bei mir ist nichts rot markiert:
![image](https://github.com/Thomas-Mielke-Software/ECTElster/assets/11477743/6f1e18ec-b8eb-4d6c-8cf8-5d17eaaf2975)

Aktuelle Version 3.8 des Plugin ist auch installiert?
In dem Fall befürchte ich, dass der Fehler tatsächlich im Detail liegt und nur noch hilft, mir die live-Daten zu schicken (easct.ini + JahrXXXX.eca), am Besten per EMail an thomas-ät-mielke.software . 

[PS: Ich merke gerade, dass die 3000 € gar nicht extra aufgeführt sind...]

**Comment by thomiel** [comment]
Hier fehlte was in der Datei EUeR-d-2023.ecf im EC&T-Programmverzeichnis

<feld id="1240" typ="Ausgaben" seite="3" horizontal="929" vertikal="764" ausrichtung="rechtsbuendig" anteil="netto" nachkommaanteil="mit" nullwertdarstellung="nein" veraltet="nein" unterkategorie="Korrektur des Gewinns" **_elsterfeldname="Ermittlung_Gewinn/P3_26_26a_26b_abziehbar/Sum/E6007203"_**>

So sieht es schon besser aus:
![image](https://github.com/Thomas-Mielke-Software/ECTElster/assets/11477743/3ac36eb5-0d8b-46ef-a5ee-96946148a904)

Bis ich den Fix offiziell veröffentliche, einfach die [.ecf-datei](https://github.com/Thomas-Mielke-Software/EasyCash/blob/master/EUeR/2023/EUeR-d-2023.ecf) herunterladen und mit Administrator-Berechtigung in das EC&T-Programmverzeichnis speichern.
![image](https://github.com/Thomas-Mielke-Software/ECTElster/assets/11477743/e1cb73c3-6884-4766-8009-2c85e19ebc9c)

https://github.com/Thomas-Mielke-Software/EasyCash/commit/750598e1396ec3feaa337adaa1ff7f6e27a23f69
